name: Publish

on:
  push:
    branches:
      - main
      - build

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - uses: golangci-lint/golangci-lint-action@v3
        with:
          version: v1.54

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - uses: ./.github/actions/test

  publish:
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-git
      - id: version
        run: |
          echo version=$(jq -r .version version.json) >> $GITHUB_OUTPUT
      - run: |
          git tag -a v${{ steps.version.outputs.version }} -m "v${{ steps.version.outputs.version }}"
          #git push origin v${{ steps.version.outputs.version }}
