name: Publish

on:
  push:
    branches:
      - main
      - build

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          go-version: "1.21"

  publish:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - id: version
        run: |
          echo version=$(jq -r .version version.json) >> $GITHUB_OUTPUT
      - run: |
          git tag -a v${{ steps.version.outputs.version }} -m "v${{ steps.version.outputs.version }}"
          #git push origin v${{ steps.version.outputs.version }}
