name: Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: version
        run: |
          echo version=$(jq -r .version version.json) >> $GITHUB_OUTPUT
      - run: |
          git fetch --tags
          if git rev-parse v${{ steps.version.outputs.version }} >/dev/null 2>&1; then
            echo "Error: v${{ steps.version.outputs.version }} tag already exists."
            echo "Error: Version in version.json must be incremented before publishing."
            exit 1
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - uses: ./.github/actions/test
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - check
      - lint
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-git
      - id: version
        run: |
          echo version=$(jq -r .version version.json) >> $GITHUB_OUTPUT
      - run: |
          git tag -a v${{ steps.version.outputs.version }} -m "v${{ steps.version.outputs.version }}"
          git push origin v${{ steps.version.outputs.version }}
          # Create release
          echo ${{ github.token }} | gh auth login --with-token
          gh release create v${{ steps.version.outputs.version }} --title "v${{ steps.version.outputs.version }}" --notes ""
